import * as _ from "lodash";

const tokensList = [
    "Corporation Agent",
    "Corporation Agent.1",
    "Credit",
    "Credit.1",
    "Credit.2",
    "Credit.3",
    "Credit.4",
    "Credit.5",
    "Equipment",
    "Equipment.1",
    "Equipment.2",
    "Equipment.3",
    "Equipment.4",
    "Equipment.5",
    "Equipment.6",
    "Equipment.7",
    "Equipment.8",
    "Equipment.9",
    "Equipment.10",
    "Equipment.11",
    "Fighter",
    "Fighter.1",
    "Hologram",
    "Hologram.1",
    "Hologram.2",
    "Hologram.3",
    "Mech",
    "Mech.1",
    "Mech.2",
    "Mech.3",
    "Mech.4",
    "Mech.5",
    "Mech.6",
    "Mech.7",
    "Mech.8",
    "Military",
    "Military.1",
    "Military.2",
    "Military.3",
    "Mutant",
    "Mutant.1",
    "Shaitan",
    "Wildschwein",
    "Xeno Propagator",
    "Xeno Propagator.1",
    "Xeno Propagator.2",
    "Xeno Scion",
    "Xeno Scion.1",
    "Xeno Scion.2",
    "Xeno Scion.3"
];

export default _.map(tokensList, tokenName => {
    return `../dist/${require(`../common/resources/tokenImages/${tokenName}.jpg`)}`;
});