import * as _ from "lodash";

const updatesList = [
    "Archive Virus",
    "Bodyguard Drones",
    "Amlich Security",
    "Bergstadt Justice",
    "Biomech Team",
    "Cryonics Facility",
    "Community Officer",
    "De Bruijn Air Platform",
    "Head Detective",
    "Keep the Peace",
    "Special Circumstances",
    "Suspension Squad",
    "Topple",
    "Wartime Recruitment",
    "Arrester Droid",
    "Atmospheric Survey",
    "Coordinate Scrambler",
    "Deep Freeze",
    "Grasp the Dimensions",
    "Lambert Stealth Bomber",
    "Neural Implants",
    "Supercoolant Technician",
    "Tactical Freeze Ray",
    "Umida Biotech Incorporated",
    "Umida Security Protocols",
    "Cloning Vats",
    "Figment of Death",
    "Inside Infiltration",
    "The Left Hand",
    "Mortality",
    "Sink into the Oceans",
    "Smuggling Routes",
    "Warapur Contract",
    "Al Maham Assurance",
    "Blitz Agent",
    "Charge Captain",
    "Chentsov Scylla",
    "Hyperadrenaline",
    "Rip Space-Time",
    "Rocket Salvo",
    "Slipstream Hunter",
    "Speed Demon",
    "Supervolcanic Fallout",
    "Supply Runner",
    "Al Maham Traders",
    "Brood Ambush",
    "Deep into the Subconscious",
    "Deep Jungle Hunter",
    "Failed Kushak Subject",
    "Kushak Interference",
    "Kushak R&D, Basirah Branch",
    "Unstable Growth",
    "Wings of the Law",
    "Canyon Skitterer",
    "Sewer Dredgers",
    "Extraterrestrial Colony",
    "Hexaferrum Mine",
    "Hyperium Mine",
    "Orichalcix Mine",
    "Quadrinix Mine",
    "Siderite Mine",
];

export default _.map(updatesList, cardName => {
    return `../dist/${require(`../common/resources/images/${cardName}.jpg`)}`;
});